# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  sweetlionheart.com:
    site_hosts:
    - canonical: sweetlionheart.com
    local_path: ../site
    branch: master
    repo: git@github.com:taahirisaacs/sweetlionheart.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
